# Generated by Django 3.1.2 on 2020-10-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughts',
            name='ThoughtImportant',
            field=models.BooleanField(default=False),
        ),
    ]
